//challenge number 2: printing odd numbers less than 100

var a = 1;
for(a=1;a<=100;a+=2){
        console.log(a);
}

//challenge number 3:printing multiplication table with 7
var b = 1;
for(b=1;b<=12;b++){
    var c = b*7;
    console.log(c);
}

//challenge number 4: tabulate multiplication tables with numbers from 1 to 12.

const d = parseInt(prompt('Enter an Integer:'));

for(e=1;e<=12;e++){
    const result = e*d;
    return result;
    //console.log(`${d}*${e}={result}`)
}


